Fix deploiement Vercel:
src/components/ui/invoices/table.tsx(115,26): error TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & Omit<{ id: string; }, `${string}$`> & _Only$<{ id: string; }> & ComponentBaseProps & { children?: JSXChildren; }'.
  Property 'id' is missing in type '{}' but required in type 'Omit<{ id: string; }, `${string}$`>'.